<script setup>
import useRawLayout from '@/layouts/useRawLayout';

const rawLayout = useRawLayout()

//
</script>

<template>
  <div>
    <VRow>
      <VCol cols="12">
       <VSkeletonLoader type="table" />
      </VCol>
    </VRow>
    

    <div id="company-loading-bg">
      <div class="loading-logo">
        <!-- SVG Logo -->
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(255, 255, 255, 0); display: block; shape-rendering: auto;" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
          <circle cx="50" cy="50" r="32" stroke-width="8" stroke="#e15b64" stroke-dasharray="50.26548245743669 50.26548245743669" fill="none" stroke-linecap="round">
            <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
          </circle>
          <circle cx="50" cy="50" r="23" stroke-width="8" stroke="#f8b26a" stroke-dasharray="36.12831551628262 36.12831551628262" stroke-dashoffset="36.12831551628262" fill="none" stroke-linecap="round">
            <animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;-360 50 50"></animateTransform>
          </circle>
          <!-- [ldio] generated by https://loading.io/ -->
        </svg>
      </div>
    </div>
  </div>
</template>


<style scoped lang="scss">
  .company-nav-card {
    height: auto !important;
    @media screen and (min-width: 1280px) {
      min-height: calc(100vh - calc( 69.97px + 24px ));
    }
  }

  #company-loading-bg {
    position: absolute;
    top: 0;
    left: 0;
    z-index: 1000000;
    display: block;
    backdrop-filter: blur(2px);
    background: transparent !important;
    block-size: 100%;
    inline-size: 100%;
  }

</style>


